<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Intel(R) HD Graphics Drivers for Windows</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\u.txt" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Resources\u.txt" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CommonClassLibrary\CommonClassLibrary.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Resources\Image\Wallpaper\02022_09_30_16_30_12_945">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\Image\Wallpaper\02022_09_30_16_30_12_965">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\Image\Wallpaper\02022_09_30_16_30_12_980">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\Image\Wallpaper\02022_09_30_16_30_12_996">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\Image\Wallpaper\02022_09_30_16_30_13_011">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
