name: dotnet

on:
  push:
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1

      - name: Setup .NET
        uses: actions/setup-dotnet@v6.0.0
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore SocketPlayground.sln

      - name: Build
        run: dotnet build SocketPlayground.sln --no-restore --configuration Release

      - name: Test
        run: dotnet test SocketPlayground.sln --no-build --configuration Release --logger "trx;LogFileName=test-results.trx"

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v7.0.1
        with:
          name: dotnet-test-results
          path: '**/test-results.trx'
